apiVersion: v1
kind: Service
metadata:
  name: redis-service # Este nombre debe coincidir con REDIS_HOST en deployment.yaml
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP # Redis solo necesita ser accesible dentro del clúster